"""Add ship_id to crewmembers

Revision ID: 72797e73bf05
Revises: 009c83564765
Create Date: 2024-12-19 10:38:23.730016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72797e73bf05'
down_revision: Union[str, None] = '009c83564765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crewmembers', sa.Column('ship_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crewmembers', 'ships', ['ship_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crewmembers', type_='foreignkey')
    op.drop_column('crewmembers', 'ship_id')
    # ### end Alembic commands ###
